# Generated by Django 2.2.5 on 2023-11-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Gin', 'Gin'), ('Vodka', 'Vodka'), ('Rum', 'Rum'), ('Tequila', 'Tequila'), ('Whiskey', 'Whiskey')], max_length=60)),
                ('CocktailName', models.CharField(blank=True, default='', max_length=60)),
                ('Bar_or_Restaurant', models.CharField(blank=True, default='', max_length=60)),
                ('City', models.CharField(blank=True, default='', max_length=60)),
                ('State', models.CharField(blank=True, default='', max_length=2)),
                ('Description', models.CharField(blank=True, default='', max_length=300)),
                ('User', models.CharField(blank=True, default='', max_length=60)),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
